# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# # By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
number = 1
prev_number = 0
new_number = 0
count = 0
while number < 4000000:

    if number%2==0:
        count = count + number

    new_number = number + prev_number
    prev_number = number
    number = new_number

print(count)